# -*- coding: utf-8 -*-
"""Recommendation System with LDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16bhqWnBLVfd1WwQvC28prmRSRUnEF0Wj

News Article Recommendation  System using LDA topic Modeling
"""

!pip install ktrain

import os

import numpy as np
import pandas as pd

import ktrain
from ktrain import text
from sklearn.datasets import fetch_20newsgroups

remove=('headers','footers','quotes')
test = fetch_20newsgroups(subset='test', remove=remove)
train = fetch_20newsgroups(subset='train', remove=remove)

texts = train.data+test.data

# Commented out IPython magic to ensure Python compatibility.
# %%time
# tm=ktrain.text.get_topic_model(texts, n_features=10000)

tm.build(texts, threshold=0.25)

tm.train_recommender()

categories=['rec.sport.baseball','sci.space','sci.med','comp.graphics','rec.motorcycles']

rawtext="""There are still weeks left to go in the 2022 MLB regular season, but a few teams are already looking toward October.

The Dodgers have officially secured the season's first playoff berth, and the Houston Astros and New York Mets followed next. Meanwhile, clubs such as the Seattle Mariners, Tampa Bay Rays, Philadelphia Phillies and San Diego Padres, are battling it out for the remaining wild-card spots. Beyond division races, there are many storylines to watch as the regular season comes to an end and October begins, such as Seattle's attempt to break a 21-year playoff drought, Aaron Judge's race to 62 home runs and Albert Pujols' quest for 700 career home runs. """



tm.recommend(text=rawtext, n=5)

for i, doc in enumerate(tm.recommend(text=rawtext, n=5)):
  print('Similar articles #%s'%(i+1))
  print('Text \n')
  print(" ".join(doc['text'].split()[:500]))